bundle:
  name: credit-lending-etl

targets:
  dev:
    mode: development
    default: true
    workspace:
      host: https://adb-<your-workspace-id>.<region>.azuredatabricks.net

  prod:
    mode: production
    workspace:
      host: https://adb-<your-workspace-id>.<region>.azuredatabricks.net

resources:
  jobs:

    credit_lending_raw_job:
      name: credit-lending-raw

      tasks:
        - task_key: raw_ingestion
          job_cluster_key: shared_cluster
          spark_python_task:
            python_file: ../ingestion/raw/raw.py
            parameters:
              - "--config"
              - "../config/pipelines.yml"

    credit_lending_silver_job:
      name: credit-lending-silver

      tasks:
        - task_key: silver_processing
          job_cluster_key: shared_cluster
          spark_python_task:
            python_file: ../ingestion/silver/silver.py
            parameters:
              - "--config"
              - "../config/pipelines.yml"

    credit_lending_gold_job:
      name: credit-lending-gold

      tasks:
        - task_key: gold_processing
          job_cluster_key: shared_cluster
          spark_python_task:
            python_file: ../ingestion/gold/gold.py
            parameters:
              - "--config"
              - "../config/pipelines.yml"

  job_clusters:
    - job_cluster_key: shared_cluster
      new_cluster:
        spark_version: 13.3.x-scala2.12
        node_type_id: Standard_DS3_v2
        num_workers: 2
        autotermination_minutes: 60
